In [37]:
!pip install pymongo pandas

Requirement already satisfied: pymongo in /usr/local/python/3.11.15/lib/python3.11/site-packages (4.16.0)
Requirement already satisfied: pandas in /usr/local/python/3.11.15/lib/python3.11/site-packages (3.0.1)
Requirement already satisfied: dnspython<3.0.0,>=2.6.1 in /usr/local/python/3.11.15/lib/python3.11/site-packages (from pymongo) (2.8.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/python/3.11.15/lib/python3.11/site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/python/3.11.15/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/python/3.11.15/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [38]:
from pymongo import MongoClient
import pandas as pd
from datetime import datetime

In [39]:
client = MongoClient("mongodb://root:rootpass@localhost:27017")
print(client.server_info()["version"])

8.2.6

In [40]:
db = client['loja']
colecao = db['vendas']

In [41]:
dados = [ { "cliente": "Ana", "produto": "Mouse", "categoria": "Informática", "quantidade": 2, "preco_unitario": 50, "cidade": "Ourinhos", "data": datetime(2026, 3, 1), "forma_pagamento": "Cartão" }, { "cliente": "Bruno", "produto": "Teclado", "categoria": "Informática", "quantidade": 1, "preco_unitario": 120, "cidade": "Jacarezinho", "data": datetime(2026, 3, 2), "forma_pagamento": "Pix" }, { "cliente": "Carla", "produto": "Caderno", "categoria": "Papelaria", "quantidade": 5, "preco_unitario": 15, "cidade": "Ourinhos", "data": datetime(2026, 3, 2), "forma_pagamento": "Dinheiro" }, { "cliente": "Daniel", "produto": "Caneta", "categoria": "Papelaria", "quantidade": 10, "preco_unitario": 3, "cidade": "Salto Grande", "data": datetime(2026, 3, 3), "forma_pagamento": "Pix" }, { "cliente": "Elaine", "produto": "Monitor", "categoria": "Informática", "quantidade": 1, "preco_unitario": 900, "cidade": "Ourinhos", "data": datetime(2026, 3, 3), "forma_pagamento": "Cartão" }, { "cliente": "Fabio", "produto": "Mochila", "categoria": "Acessórios", "quantidade": 2, "preco_unitario": 80, "cidade": "Jacarezinho", "data": datetime(2026, 3, 4), "forma_pagamento": "Boleto" }, { "cliente": "Gabriela", "produto": "Livro", "categoria": "Livros", "quantidade": 3, "preco_unitario": 40, "cidade": "Ourinhos", "data": datetime(2026, 3, 4), "forma_pagamento": "Pix" }, { "cliente": "Henrique", "produto": "Fone", "categoria": "Informática", "quantidade": 2, "preco_unitario": 150, "cidade": "Assis", "data": datetime(2026, 3, 5), "forma_pagamento": "Cartão" }, { "cliente": "Isabela", "produto": "Agenda", "categoria": "Papelaria", "quantidade": 4, "preco_unitario": 20, "cidade": "Salto Grande", "data": datetime(2026, 3, 5), "forma_pagamento": "Dinheiro" }, { "cliente": "João", "produto": "Webcam", "categoria": "Informática", "quantidade": 1, "preco_unitario": 250, "cidade": "Ourinhos", "data": datetime(2026, 3, 6), "forma_pagamento": "Pix" } ]

In [42]:
colecao.insert_many(dados)

InsertManyResult([ObjectId('69bc9fa1149b2714dec73e15'), ObjectId('69bc9fa1149b2714dec73e16'), ObjectId('69bc9fa1149b2714dec73e17'), ObjectId('69bc9fa1149b2714dec73e18'), ObjectId('69bc9fa1149b2714dec73e19'), ObjectId('69bc9fa1149b2714dec73e1a'), ObjectId('69bc9fa1149b2714dec73e1b'), ObjectId('69bc9fa1149b2714dec73e1c'), ObjectId('69bc9fa1149b2714dec73e1d'), ObjectId('69bc9fa1149b2714dec73e1e')], acknowledged=True)

In [43]:
dados_mongo = list(colecao.find({
    "preco_unitario": {"$gte" : 100, "$lte" : 300}
}))

display(dados_mongo)

[{'_id': ObjectId('69bc9928149b2714dec73e0b'),
  'cliente': 'Bruno',
  'produto': 'Teclado',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 120,
  'cidade': 'Jacarezinho',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69bc9928149b2714dec73e11'),
  'cliente': 'Henrique',
  'produto': 'Fone',
  'categoria': 'Informática',
  'quantidade': 2,
  'preco_unitario': 150,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69bc9928149b2714dec73e13'),
  'cliente': 'João',
  'produto': 'Webcam',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 250,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69bc9fa1149b2714dec73e16'),
  'cliente': 'Bruno',
  'produto': 'Teclado',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 120,
  'cidade': 'Jacarezinho',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69bc9fa1149b2714dec73e1c'),
  'cliente': 'Henrique',
  'produto': 'Fone',
  'categoria': 'Informática',
  'quantidade': 2,
  'preco_unitario': 150,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69bc9fa1149b2714dec73e1e'),
  'cliente': 'João',
  'produto': 'Webcam',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 250,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'}]

In [44]:
dados_mongo = list(colecao.find({
    "cidade": {"$in" : ['Ourinhos', 'Assis']}
}))

display(dados_mongo)

[{'_id': ObjectId('69bc9928149b2714dec73e0a'),
  'cliente': 'Ana',
  'produto': 'Mouse',
  'categoria': 'Informática',
  'quantidade': 2,
  'preco_unitario': 50,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69bc9928149b2714dec73e0c'),
  'cliente': 'Carla',
  'produto': 'Caderno',
  'categoria': 'Papelaria',
  'quantidade': 5,
  'preco_unitario': 15,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69bc9928149b2714dec73e0e'),
  'cliente': 'Elaine',
  'produto': 'Monitor',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 900,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 3, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69bc9928149b2714dec73e10'),
  'cliente': 'Gabriela',
  'produto': 'Livro',
  'categoria': 'Livros',
  'quantidade': 3,
  'preco_unitario': 40,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69bc9928149b2714dec73e11'),
  'cliente': 'Henrique',
  'produto': 'Fone',
  'categoria': 'Informática',
  'quantidade': 2,
  'preco_unitario': 150,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69bc9928149b2714dec73e13'),
  'cliente': 'João',
  'produto': 'Webcam',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 250,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69bc9fa1149b2714dec73e15'),
  'cliente': 'Ana',
  'produto': 'Mouse',
  'categoria': 'Informática',
  'quantidade': 2,
  'preco_unitario': 50,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69bc9fa1149b2714dec73e17'),
  'cliente': 'Carla',
  'produto': 'Caderno',
  'categoria': 'Papelaria',
  'quantidade': 5,
  'preco_unitario': 15,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69bc9fa1149b2714dec73e19'),
  'cliente': 'Elaine',
  'produto': 'Monitor',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 900,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 3, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69bc9fa1149b2714dec73e1b'),
  'cliente': 'Gabriela',
  'produto': 'Livro',
  'categoria': 'Livros',
  'quantidade': 3,
  'preco_unitario': 40,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69bc9fa1149b2714dec73e1c'),
  'cliente': 'Henrique',
  'produto': 'Fone',
  'categoria': 'Informática',
  'quantidade': 2,
  'preco_unitario': 150,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69bc9fa1149b2714dec73e1e'),
  'cliente': 'João',
  'produto': 'Webcam',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 250,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'}]

In [45]:
df = pd.DataFrame(dados_mongo)
df

,_id,cliente,produto,categoria,quantidade,preco_unitario,cidade,data,forma_pagamento
0,69bc9928149b2714dec73e0a,Ana,Mouse,Informática,2,50,Ourinhos,2026-03-01,Cartão
1,69bc9928149b2714dec73e0c,Carla,Caderno,Papelaria,5,15,Ourinhos,2026-03-02,Dinheiro
2,69bc9928149b2714dec73e0e,Elaine,Monitor,Informática,1,900,Ourinhos,2026-03-03,Cartão
3,69bc9928149b2714dec73e10,Gabriela,Livro,Livros,3,40,Ourinhos,2026-03-04,Pix
4,69bc9928149b2714dec73e11,Henrique,Fone,Informática,2,150,Assis,2026-03-05,Cartão
5,69bc9928149b2714dec73e13,João,Webcam,Informática,1,250,Ourinhos,2026-03-06,Pix
6,69bc9fa1149b2714dec73e15,Ana,Mouse,Informática,2,50,Ourinhos,2026-03-01,Cartão
7,69bc9fa1149b2714dec73e17,Carla,Caderno,Papelaria,5,15,Ourinhos,2026-03-02,Dinheiro
8,69bc9fa1149b2714dec73e19,Elaine,Monitor,Informática,1,900,Ourinhos,2026-03-03,Cartão
9,69bc9fa1149b2714dec73e1b,Gabriela,Livro,Livros,3,40,Ourinhos,2026-03-04,Pix
10,69bc9fa1149b2714dec73e1c,Henrique,Fone,Informática,2,150,Assis,2026-03-05,Cartão
11,69bc9fa1149b2714dec73e1e,João,Webcam,Informática,1,250,Ourinhos,2026-03-06,Pix

In [46]:
df.isnull().sum()

_id                0
cliente            0
produto            0
categoria          0
quantidade         0
preco_unitario     0
cidade             0
data               0
forma_pagamento    0
dtype: int64

Verificar se tem dados nulo

In [47]:
df['valor_total'] = df['quantidade'] * df['preco_unitario']
df.head(5)

,_id,cliente,produto,categoria,quantidade,preco_unitario,cidade,data,forma_pagamento,valor_total
0,69bc9928149b2714dec73e0a,Ana,Mouse,Informática,2,50,Ourinhos,2026-03-01,Cartão,100
1,69bc9928149b2714dec73e0c,Carla,Caderno,Papelaria,5,15,Ourinhos,2026-03-02,Dinheiro,75
2,69bc9928149b2714dec73e0e,Elaine,Monitor,Informática,1,900,Ourinhos,2026-03-03,Cartão,900
3,69bc9928149b2714dec73e10,Gabriela,Livro,Livros,3,40,Ourinhos,2026-03-04,Pix,120
4,69bc9928149b2714dec73e11,Henrique,Fone,Informática,2,150,Assis,2026-03-05,Cartão,300

In [48]:
faturamento = df['valor_total'].sum()
print("Faturamento Total: ", faturamento)

Faturamento Total:  3490

In [49]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   _id              12 non-null     object
 1   cliente          12 non-null     str
 2   produto          12 non-null     str
 3   categoria        12 non-null     str
 4   quantidade       12 non-null     int64
 5   preco_unitario   12 non-null     int64
 6   cidade           12 non-null     str
 7   data             12 non-null     datetime64[us]
 8   forma_pagamento  12 non-null     str
 9   valor_total      12 non-null     int64
dtypes: datetime64[us](1), int64(3), object(1), str(5)
memory usage: 1.1+ KB

In [50]:
faturamento_categoria = df.groupby('categoria')['valor_total'].sum().sort_values(ascending=False)
faturamento_categoria

categoria
Informática    3100
Livros          240
Papelaria       150
Name: valor_total, dtype: int64

In [51]:
faturamento_produto = df.groupby('produto')['valor_total'].sum().sort_values(ascending=False)
faturamento_produto

produto
Monitor    1800
Fone        600
Webcam      500
Livro       240
Mouse       200
Caderno     150
Name: valor_total, dtype: int64

In [52]:
vendas_por_cidade = df['cidade'].value_counts()
vendas_por_cidade

cidade
Ourinhos    10
Assis        2
Name: count, dtype: int64

In [55]:
media_valor_vendas = df['valor_total'].mean()
print(f"Média do  Valor das Vendas: {media_valor_vendas:.2f}")

Média do  Valor das Vendas: 290.83

In [56]:
produto_top = df.groupby("produto")['valor_total'].sum().idxmax()
produto_top

'Monitor'

produto mais vendido

In [60]:
cidade_top = df['cidade'].value_counts().idxmax()
cidade_top

'Ourinhos'

cidade com mais vendas

In [64]:
relatorio = {
    "data_geracao" : datetime.now(),
    "faturamento_total": float(faturamento),
    "faturamento_categoria" : faturamento_categoria.to_dict(),
    "produto_top" : produto_top,
    "cidade_top" : cidade_top
}

display(relatorio)

{'data_geracao': datetime.datetime(2026, 3, 20, 1, 31, 0, 193963),
 'faturamento_total': 3490.0,
 'faturamento_categoria': {'Informática': 3100,
  'Livros': 240,
  'Papelaria': 150},
 'produto_top': 'Monitor',
 'cidade_top': 'Ourinhos'}

In [65]:
colecao_relatorios = db['relatorios']
colecao_relatorios.insert_one(relatorio)

InsertOneResult(ObjectId('69bca357149b2714dec73e20'), acknowledged=True)

In [67]:
for r in colecao_relatorios.find():
    display(r)

{'_id': ObjectId('69bca357149b2714dec73e20'),
 'data_geracao': datetime.datetime(2026, 3, 20, 1, 31, 0, 193000),
 'faturamento_total': 3490.0,
 'faturamento_categoria': {'Informática': 3100,
  'Livros': 240,
  'Papelaria': 150},
 'produto_top': 'Monitor',
 'cidade_top': 'Ourinhos'}